INSERT INTO USER (LOGIN, PASSWORD, USER_NAME, AUTHORITY, ENABLED)
VALUES (
'admin',
'$2a$10$6ZGmwym8OuIL10tOk13laOEqF39w//8xqYWAByblDmK4zb3nE.krS',
'Admin',
'ROLE_ADMIN',
'true'
);

INSERT INTO USER (LOGIN, PASSWORD, USER_NAME, AUTHORITY, ENABLED)
VALUES (
'user',
'$2a$10$YAoIicDOqSCsBeqpwEL4IuN8e1tTLrjgdZ5991iBtxUKmdmUOYYqW',
'User',
'ROLE_USER',
'true'
);

